title: Md Nazmul Hasan
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://farhapartex.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
disqus_shortname: nazmul-hasan
navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: farhapartex
  # twitter: brianmaierjr
  facebook: FarHaPartex
  email: hasan08sust@gmail.com

google_analytics: "UA-142606750-1"
