title: মোঃ নাজমুল হাসান 
description: I am Nazmul Hasan. Programmer | Data Enthusiast

url: https://farhapartex.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
disqus_shortname: nazmul-hasan
navigation:
  - title: হোম
    url: /index.html
  - title: আমার সম্পর্কে
    url: /about
  - title: যোগাযোগ
    url: /contact

social:
  github: farhapartex
  # twitter: brianmaierjr
  facebook: FarHaPartex
  email: hasan08sust@gmail.com

google_analytics: "UA-142606750-1"
